bot:
  username: search on youtube
  token: 5320131110:AAH_SsMu7nFtpPNd3EYOtgj_wAQvc3uuHtc

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
