app:
  bot:
    username: search on youtube
    token: 5362160529:AAEWtcrntubP1MgiBDogWY6fK2n3zCPOzZ8
  yotube:
    token: AIzaSyBzUj8WyeAlsZ0xnOFU8nxS9fJ_plZZu_g


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
